platform :ios, '9.0'

target 'app' do
  pod 'Firebase/Core'
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
  end
end