platform :ios, '9.0'

target 'app' do
  pod 'Firebase/Core'

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'app-tvOS' do

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
