fastlane_version '2.95.0'

platform :ios do
  before_all do |lane|
    setup_travis
  end

  desc 'Clean project medatata'
  lane :clean do
    clear_derived_data
    clean_build_artifacts
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(
      app_identifier: "com.eduardomoroni.example.app",
      clone_branch_directly: true,
      shallow_clone: true,
      readonly: false,
      verbose: true,
      force: true,
    )
  end

  desc 'Build the iOS application.'
  lane :build do
    clean
    enable_automatic_code_signing(
      path: "./ios/app.xcodeproj"
    )
    certificates
    build_app(
      scheme: "app",
      project: "./ios/app.xcodeproj",
      silent: true,
      skip_archive: true,
      export_method: "development"
    )
  end

  lane :test_build do
    xcodebuild(
      archive: false,
      scheme: "app",
      project: "./ios/app.xcodeproj",
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "./ios/app.xcodeproj")
    build
    upload_to_testflight
  end
end

platform :android do
  desc 'Clean Android project.'
  lane :clean do
    gradle(task: 'clean', project_dir: 'android/')
  end

  desc 'Build the Android application.'
  lane :build do
    clean
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    build
    gradle(task: "assembleRelease")
    upload_to_play_store
  end
end